---

- hosts: windows
  tasks:
  - name: Create registry path MyCompany
    ansible.windows.win_regedit:
      path: HKCU:\Software\MyCompany
        keys:
            - name: TierLevel
                value: "tier"
            - name: Patching
                value: "patching"
