---

- hosts: windows
  tasks:
    - name: Create Software key under HKCU\Software (if needed)
      win_regedit:
        path: HKCU:\Software\MyCompany
        state: present

    - name: Create hello key in HKCU\Software\MyCompany
      win_regedit:
        path: HKCU:\Software\MyCompany\hello
        state: present
        value: world
        type: string
